import { User, Message, Notification, Contact } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Мария Петрова',
    age: 28,
    location: 'София',
    bio: 'Обичам природата, спорт и добрата музика. Търся приключения!',
    avatar: 'https://i.pravatar.cc/300?img=1',
    interests: ['Планински походи', 'Йога', 'Пътуване'],
    liked: false,
  },
  {
    id: '2',
    name: 'Иван Георгиев',
    age: 32,
    location: 'Пловдив',
    bio: 'Разработчик на софтуер, меломан и кафеман. Винаги готов за нови познанства.',
    avatar: 'https://i.pravatar.cc/300?img=12',
    interests: ['Програмиране', 'Музика', 'Кафе'],
    liked: false,
  },
  {
    id: '3',
    name: 'Елена Димитрова',
    age: 26,
    location: 'Варна',
    bio: 'Художник и мечтател. Обичам морето и изкуството във всичките му форми.',
    avatar: 'https://i.pravatar.cc/300?img=5',
    interests: ['Рисуване', 'Плаж', 'Фотография'],
    liked: false,
  },
  {
    id: '4',
    name: 'Георги Иванов',
    age: 30,
    location: 'София',
    bio: 'Предприемач и спортист. Търся активен и позитивен човек за споделяне на емоции.',
    avatar: 'https://i.pravatar.cc/300?img=15',
    interests: ['Фитнес', 'Бизнес', 'Пътуване'],
    liked: false,
  },
  {
    id: '5',
    name: 'Анна Стефанова',
    age: 27,
    location: 'Бургас',
    bio: 'Учител и книголюбител. Обичам да се смея и да създавам приятни спомени.',
    avatar: 'https://i.pravatar.cc/300?img=9',
    interests: ['Четене', 'Кино', 'Готвене'],
    liked: false,
  },
  {
    id: '6',
    name: 'Петър Николов',
    age: 35,
    location: 'София',
    bio: 'Архитект с любов към дизайна и модерното изкуство. Винаги търся вдъхновение.',
    avatar: 'https://i.pravatar.cc/300?img=13',
    interests: ['Архитектура', 'Дизайн', 'Изкуство'],
    liked: false,
  },
  {
    id: '7',
    name: 'Надежда Тодорова',
    age: 29,
    location: 'Пловдив',
    bio: 'Маркетолог и пътешественик. Обичам да опознавам нови места и хора.',
    avatar: 'https://i.pravatar.cc/300?img=10',
    interests: ['Маркетинг', 'Пътуване', 'Мода'],
    liked: false,
  },
  {
    id: '8',
    name: 'Димитър Василев',
    age: 31,
    location: 'Варна',
    bio: 'Музикант и композитор. Свиря китара и обичам да създавам нови мелодии.',
    avatar: 'https://i.pravatar.cc/300?img=14',
    interests: ['Музика', 'Китара', 'Концерти'],
    liked: false,
  },
  {
    id: '9',
    name: 'Виктория Ангелова',
    age: 25,
    location: 'София',
    bio: 'Студентка по психология. Интересувам се от човешкото поведение и емоции.',
    avatar: 'https://i.pravatar.cc/300?img=20',
    interests: ['Психология', 'Йога', 'Медитация'],
    liked: false,
  },
  {
    id: '10',
    name: 'Христо Георгиев',
    age: 33,
    location: 'Бургас',
    bio: 'Шеф-готвач с любов към кулинарията и добрата храна. Винаги експериментирам.',
    avatar: 'https://i.pravatar.cc/300?img=17',
    interests: ['Готвене', 'Храна', 'Вино'],
    liked: false,
  },
  {
    id: '11',
    name: 'Радостина Петкова',
    age: 28,
    location: 'София',
    bio: 'Дизайнер на интериори. Обичам да създавам красиви и уютни пространства.',
    avatar: 'https://i.pravatar.cc/300?img=23',
    interests: ['Дизайн', 'Интериор', 'DIY проекти'],
    liked: false,
  },
  {
    id: '12',
    name: 'Николай Стоянов',
    age: 29,
    location: 'Пловдив',
    bio: 'Фотограф и влогър. Обичам да заснемам моменти и да споделям истории.',
    avatar: 'https://i.pravatar.cc/300?img=18',
    interests: ['Фотография', 'Видео', 'Блогинг'],
    liked: false,
  },
];

export const mockMessages: Message[] = [
  {
    id: '1',
    senderId: '2',
    receiverId: 'current-user',
    content: 'Здравей! Видях профила ти и ми хареса.',
    timestamp: new Date('2025-11-19T10:30:00'),
    read: false,
  },
  {
    id: '2',
    senderId: 'current-user',
    receiverId: '2',
    content: 'Здрасти! Благодаря, и аз харесах твоя профил.',
    timestamp: new Date('2025-11-19T10:35:00'),
    read: true,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'like',
    userId: '1',
    userName: 'Мария Петрова',
    content: 'Мария Петрова харесва твоя профил',
    timestamp: new Date('2025-11-19T09:00:00'),
    read: false,
  },
  {
    id: '2',
    type: 'message',
    userId: '2',
    userName: 'Иван Георгиев',
    content: 'Ти имаш ново съобщение от Иван Георгиев',
    timestamp: new Date('2025-11-19T10:30:00'),
    read: false,
  },
  {
    id: '3',
    type: 'match',
    userId: '3',
    userName: 'Елена Димитрова',
    content: 'Вие и Елена Димитрова се харесахте взаимно!',
    timestamp: new Date('2025-11-19T08:15:00'),
    read: true,
  },
];

export const mockContacts: Contact[] = [
  {
    id: '1',
    userId: '2',
    user: mockUsers[1],
    lastMessage: 'Здрасти! Благодаря, и аз харесах твоя профил.',
    lastMessageTime: new Date('2025-11-19T10:35:00'),
    unreadCount: 0,
  },
  {
    id: '2',
    userId: '3',
    user: mockUsers[2],
    lastMessage: 'Здравей! Как си?',
    lastMessageTime: new Date('2025-11-19T09:20:00'),
    unreadCount: 2,
  },
  {
    id: '3',
    userId: '1',
    user: mockUsers[0],
    lastMessage: 'Имаш ли време да излезем за кафе?',
    lastMessageTime: new Date('2025-11-19T08:45:00'),
    unreadCount: 1,
  },
];
